src/Entity/Ticker.php
<?php

namespace App\Entity;

use App\Repository\TickerRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=TickerRepository::class)
 */
class Ticker
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="date", nullable=false)
     */
    private $date;

    /**
     * @ORM\Column(type="float", nullable=false)
     */
    private $open;

    /**
     * @ORM\Column(type="float", nullable=false)
     */
    private $hight;

    /**
     * @ORM\Column(type="float", nullable=false)
     */
    private $low;

    /**
     * @ORM\Column(type="float", nullable=false)
     */
    private $close;

    /**
     * @ORM\Column(type="float", nullable=false)
     */
    private $adj_close;

    /**
     * @ORM\Column(type="bigint", nullable=false)
     */
    private $volume;

    /**
     * @ORM\Column(type="string", length=255, nullable=false)
     */
    private $symbol;

    /**
     * @ORM\ManyToOne(targetEntity=Stock::class, inversedBy="tickers")
     * @ORM\JoinColumn(nullable=false)
     */
    private $stock;


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDate(): ?\DateTimeInterface
    {
        return $this->date;
    }

    public function setDate(?\DateTimeInterface $date): self
    {
        $this->date = $date;

        return $this;
    }

    public function getOpen(): ?float
    {
        return $this->open;
    }

    public function setOpen(?float $open): self
    {
        $this->open = $open;

        return $this;
    }

    public function getHight(): ?float
    {
        return $this->hight;
    }

    public function setHight(?float $hight): self
    {
        $this->hight = $hight;

        return $this;
    }

    public function getLow(): ?float
    {
        return $this->low;
    }

    public function setLow(?float $low): self
    {
        $this->low = $low;

        return $this;
    }

    public function getClose(): ?float
    {
        return $this->close;
    }

    public function setClose(?float $close): self
    {
        $this->close = $close;

        return $this;
    }

    public function getAdjClose(): ?float
    {
        return $this->adj_close;
    }

    public function setAdjClose(?float $adj_close): self
    {
        $this->adj_close = $adj_close;

        return $this;
    }

    public function getVolume(): ?string
    {
        return $this->volume;
    }

    public function setVolume(?string $volume): self
    {
        $this->volume = $volume;

        return $this;
    }

    public function getSymbol(): ?string
    {
        return $this->symbol;
    }

    public function setSymbol(?string $symbol): self
    {
        $this->symbol = $symbol;

        return $this;
    }

    public function getStock(): ?Stock
    {
        return $this->stock;
    }

    public function setStock(?Stock $stock): self
    {
        $this->stock = $stock;

        return $this;
    }

}

src/Form/TickerType.php
<?php

namespace App\Form;

use App\Entity\Ticker;
use App\Repository\StockRepository;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\NumberType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class TickerType extends AbstractType
{
    /**
     * @var StockRepository
     */
    private $repository;

    public function __construct(StockRepository $repository)
    {
        $this->repository = $repository;
    }

    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('date', null, ['widget' => 'single_text', 'attr' => ['class' => 'form-control']])
            ->add('open', null, ['attr' => ['class' => 'form-control']])
            ->add('hight', null, ['attr' => ['class' => 'form-control']])
            ->add('low', null, ['attr' => ['class' => 'form-control']])
            ->add('close', null, ['attr' => ['class' => 'form-control']])
            ->add('adj_close', null, ['attr' => ['class' => 'form-control']])
            ->add('volume', null, ['attr' => ['class' => 'form-control']])
            ->add('symbol', null, ['attr' => ['class' => 'form-control']])
            ->add('stock', ChoiceType::class, ['choices' => $this->repository->findAll(), 'choice_label' => "symbol", 'placeholder' => "select Stock", 'choice_value' => 'id', 'attr' => ['class' => 'form-control']]);
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Ticker::class,
        ]);
    }
}

src/Controller/TickerController.php
<?php

namespace App\Controller;

use App\Entity\Ticker;
use App\Form\TickerType;
use App\Repository\TickerRepository;
use Psr\Log\LoggerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Form\FormError;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("admin/ticker")
 */
class TickerController extends AbstractController
{
    /**
     * @var TickerRepository
     */
    private $tickerRepository;
    /**
     * @var LoggerInterface
     */
    private $logger;

    public function __construct(TickerRepository $tickerRepository, LoggerInterface $logger)
    {
        $this->tickerRepository = $tickerRepository;
        $this->logger = $logger;

    }

    /**
     * @Route("/", name="ticker_index", methods={"GET"})
     * @param Request $request
     * @return Response
     * return ticker page with pagination
     */
    public function index(Request $request): Response
    {
        $page = $request->query->get('p');
        $pages = null;
        if (!$page || !is_numeric($page)) {
            $page = 0;
        }
        $total = $this->tickerRepository->count([]);
        $pages = ceil($total / 10);
        return $this->render('ticker/index.html.twig', [
            'tickers' => $this->tickerRepository->getPaginated($page),
            'total' => $total,
            'pages' => $pages,
            'page' => $page,
            'symbol' => '',
        ]);
    }

    /**
     * @Route("/search", name="ticker_search", methods={"POST"})
     * @param Request $request
     * @return Response
     * search ticker page
     */
    public function search(Request $request): Response
    {
        $symbol = $request->request->get('symbol');
        if (!$symbol || !isset($symbol)) {
            $page = 0;
            $total = $this->tickerRepository->count([]);
            $pages = ceil($total / 10);
            return $this->render('ticker/index.html.twig', [
                'tickers' => $this->tickerRepository->getPaginated($page),
                'total' => $total,
                'pages' => $pages,
                'page' => $page,
                'symbol' => '',
            ]);
        }
        return $this->render('ticker/index.html.twig', [
            'tickers' => $this->tickerRepository->findAllBySymbolLike($symbol),
            'pages' => 0,
            'symbol' => $symbol,
        ]);
    }

    /**
     * @Route("/new", name="ticker_new", methods={"GET","POST"})
     * create new ticker page
     * @param Request $request
     * @return Response
     */
    public function new(Request $request): Response
    {
        $ticker = new Ticker();
        $form = $this->createForm(TickerType::class, $ticker);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            if ($this->tickerRepository->findByDateAndSymbol($ticker->getDate(), $ticker->getSymbol())) {
                $form->addError(new FormError("Entries with the same Date and Stock cannot exist "));
                return $this->render('ticker/new.html.twig', [
                    'ticker' => $ticker,
                    'form' => $form->createView(),
                ]);
            }
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($ticker);
            $entityManager->flush();

            return $this->redirectToRoute('ticker_index');
        }

        return $this->render('ticker/new.html.twig', [
            'ticker' => $ticker,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}/edit", name="ticker_edit", methods={"GET","POST"})
     * @param Request $request
     * @param Ticker $ticker
     * @return Response
     * edit ticker page
     */
    public function edit(Request $request, Ticker $ticker): Response
    {
        $form = $this->createForm(TickerType::class, $ticker);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            if ($this->tickerRepository->findByDateAndSymbolAndNotId($ticker->getDate(), $ticker->getSymbol(), $ticker->getId())) {
                $form->addError(new FormError("Entries with the same Date and Stock cannot exist "));
                return $this->render('ticker/new.html.twig', [
                    'ticker' => $ticker,
                    'form' => $form->createView(),
                ]);
            }
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('ticker_index');
        }

        return $this->render('ticker/edit.html.twig', [
            'ticker' => $ticker,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="ticker_delete", methods={"POST"})
     * @param Request $request
     * @param Ticker $ticker
     * @return Response
     * delete ticker
     */
    public function delete(Request $request, Ticker $ticker): Response
    {
        if ($this->isCsrfTokenValid('', $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($ticker);
            $entityManager->flush();
        }

        return $this->redirectToRoute('ticker_index');
    }
}

templates/ticker/_delete_form.html.twig
<form method="post" action="{{ path('ticker_delete', {'id': ticker.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ ticker.id) }}">
    <button class="btn">Delete</button>
</form>

templates/ticker/_form.html.twig
{% block javascripts %}
    {{ encore_entry_script_tags('ticker') }}
{% endblock %}
<div class="text-center container ">
    {{ form_start(form) }}
    {% for error in form.vars.errors %}
        <div class="alert alert-danger">{{ error.message }} </div>
    {% endfor %}
    <div class="form-group row">
        <label for="ticker_stock" class="col-sm-2 col-form-label">Stock</label>
        <div class="col-sm-10">
            {{ form_widget(form.stock) }}
            {% for error in form.stock.vars.errors %}
                <div class="alert alert-danger">{{ error.message }} </div>
            {% endfor %}
        </div>

    </div>

    <div class="form-group row">
        <label for="ticker_date" class="col-sm-2 col-form-label">date</label>
        <div class="col-sm-10">
            {{ form_widget(form.date) }}
            {% for error in form.date.vars.errors %}
                <div class="alert alert-danger">{{ error.message }} </div>
            {% endfor %}
        </div>

    </div>
    <div class="form-group row">
        <label for="ticker_open" class="col-sm-2 col-form-label">open</label>
        <div class="col-sm-10">
            {{ form_widget(form.open) }}
            {% for error in form.open.vars.errors %}
                <div class="alert alert-danger">{{ error.message }} </div>
            {% endfor %}
        </div>

    </div>
    <div class="form-group row">
        <label for="ticker_hight" class="col-sm-2 col-form-label">high</label>
        <div class="col-sm-10">
            {{ form_widget(form.hight) }}
            {% for error in form.hight.vars.errors %}
                <div class="alert alert-danger">{{ error.message }} </div>
            {% endfor %}
        </div>

    </div>
    <div class="form-group row">
        <label for="ticker_low" class="col-sm-2 col-form-label">low</label>
        <div class="col-sm-10">
            {{ form_widget(form.low) }}
            {% for error in form.low.vars.errors %}
                <div class="alert alert-danger">{{ error.message }} </div>
            {% endfor %}
        </div>

    </div>
    <div class="form-group row">
        <label for="ticker_close" class="col-sm-2 col-form-label">close</label>
        <div class="col-sm-10">
            {{ form_widget(form.close) }}
            {% for error in form.close.vars.errors %}
                <div class="alert alert-danger">{{ error.message }} </div>
            {% endfor %}
        </div>

    </div>
    <div class="form-group row">
        <label for="ticker_adj_close" class="col-sm-2 col-form-label">adj_close</label>
        <div class="col-sm-10">
            {{ form_widget(form.adj_close) }}
            {% for error in form.adj_close.vars.errors %}
                <div class="alert alert-danger">{{ error.message }} </div>
            {% endfor %}
        </div>

    </div>
    <div class="form-group row">
        <label for="ticker_volume" class="col-sm-2 col-form-label">volume</label>
        <div class="col-sm-10">
            {{ form_widget(form.volume) }}
            {% for error in form.volume.vars.errors %}
                <div class="alert alert-danger">{{ error.message }} </div>
            {% endfor %}
        </div>

    </div>
    <div class="form-group row" style="display:none;">
        <label for="ticker_symbol" class="col-sm-2 col-form-label">symbol</label>
        <div class="col-sm-10">
            {{ form_widget(form.symbol) }}
            {% for error in form.symbol.vars.errors %}
                <div class="alert alert-danger">{{ error.message }} </div>
            {% endfor %}
        </div>

    </div>
    <button class="btn btn-primary btn-lg">{{ button_label|default('Save') }}</button>
    {{ form_end(form) }}

</div>

templates/ticker/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Ticker{% endblock %}

{% block body %}
    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h1 class="h2">Edit Ticker</h1>
        <div class="btn-toolbar mb-2 mb-md-0">
            <div class="btn-group me-2">
                <a  href="{{ path('ticker_index') }}" class="btn btn-sm btn-outline-info btn-lg">Back</a>
            </div>
        </div>
    </div>

    {{ include('ticker/_form.html.twig', {'button_label': 'Update'}) }}
{% endblock %}

templates/ticker/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Ticker index{% endblock %}
  {% block javascripts %}
      {{ encore_entry_script_tags('ticker') }}

  {% endblock %}

{% block body %}
    <input type="hidden" id="urls" data-index="{{ url('ticker_index') }}">

    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h1 class="h2">Tickers</h1>
        <div class="btn-toolbar mb-2 mb-md-0">
            <div class="btn-group me-2">
                <a href="{{ path('ticker_new') }}" class="btn btn-big btn-primary">Create</a>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col">
            <form action="{{ url('ticker_search') }}" method="POST">
                <div class="input-group mb-3">

                    <input type="hidden" name="_token" value="{{ csrf_token('') }}"/>
                    <input type="text" class="form-control" name="symbol" value="{{ symbol }}" placeholder="Search" aria-label="Search" aria-describedby="basic-addon2">
                    <div class="input-group-append">
                        <button class="btn btn-outline-primary" type="submit">Search</button>
                        {% if symbol !='' %}
                            <button class="btn btn-outline-danger " id='cancel_search' type="reset">Cancel</button>
                        {% endif %}

                    </div>
                </div>
            </form>
        </div>
        <div class="col">
            {% if pages and pages > 0 %}
                {{ include('util/paginator.html.twig', {'index':'ticker_index'}) }}
            {% endif %}
        </div>


    </div>
    <table class="table table-dark table-striped">
        <thead>
            <tr>
                <th>Id</th>
                <th>Date</th>
                <th>Open</th>
                <th>Hight</th>
                <th>Low</th>
                <th>Close</th>
                <th>Adj_close</th>
                <th>Volume</th>
                <th>Symbol</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for ticker in tickers %}
            <tr>
                <td>{{ ticker.id }}</td>
                <td>{{ ticker.date ? ticker.date|date('Y-m-d') : '' }}</td>
                <td>{{ ticker.open }}</td>
                <td>{{ ticker.hight }}</td>
                <td>{{ ticker.low }}</td>
                <td>{{ ticker.close }}</td>
                <td>{{ ticker.adjClose }}</td>
                <td>{{ ticker.volume }}</td>
                <td>{{ ticker.symbol }}</td>
                <td>
                    <div class="btn-toolbar mb-2 mb-md-0">
                        <div class="btn-group me-2">
                            <a type="button" class="btn btn-big btn-info edit_btn"  href="{{ path('ticker_edit', {'id': ticker.id}) }}">Edit</a>
                            <button class="btn btn-sm btn-danger delete_btn" data-toggle="modal"  data-url="{{ url('ticker_delete', {'id': ticker.id}) }}" data-target="#delete_Item">Delete</button>
                        </div>
                    </div>
                </td>
            </tr>
        {% else %}
            <tr class="text-center">
                <td colspan="10">no records found</td>
            </tr>
        {% endfor %}

        </tbody>
    </table>
    <div class="modal fade" id="delete_Item" tabindex="-1" role="dialog" aria-labelledby="delete_Item" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <form id="deleteItemForm" action="" method="post">
                <div class="modal-header">
                    <h5 class="modal-title" id="delete_Item">Delete Ticker</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <div>
                        <input type="hidden" name="_token" value="{{ csrf_token('') }}"/>
                            <h5>Are you sure you want to delete this Ticker?</h5>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                    <button type="submit" id="delete_item_submit" class="btn btn-danger" >Save changes</button>
                </div>
                </form>
            </div>
        </div>
    </div>

{% endblock %}

templates/ticker/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Ticker{% endblock %}

{% block body %}
    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h1 class="h2">Create new Ticker</h1>
        <div class="btn-toolbar mb-2 mb-md-0">
            <div class="btn-group me-2">
                <a  href="{{ path('ticker_index') }}" class="btn btn-sm btn-outline-info btn-lg">Back</a>
            </div>
        </div>
    </div>
    {{ include('ticker/_form.html.twig') }}

{% endblock %}

templates/ticker/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Ticker{% endblock %}

{% block body %}
    <h1>Ticker</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ ticker.id }}</td>
            </tr>
            <tr>
                <th>Date</th>
                <td>{{ ticker.date ? ticker.date|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Open</th>
                <td>{{ ticker.open }}</td>
            </tr>
            <tr>
                <th>Hight</th>
                <td>{{ ticker.hight }}</td>
            </tr>
            <tr>
                <th>Low</th>
                <td>{{ ticker.low }}</td>
            </tr>
            <tr>
                <th>Close</th>
                <td>{{ ticker.close }}</td>
            </tr>
            <tr>
                <th>Adj_close</th>
                <td>{{ ticker.adjClose }}</td>
            </tr>
            <tr>
                <th>Volume</th>
                <td>{{ ticker.volume }}</td>
            </tr>
            <tr>
                <th>Symbol</th>
                <td>{{ ticker.symbol }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('ticker_index') }}">back to list</a>

    <a href="{{ path('ticker_edit', {'id': ticker.id}) }}">edit</a>

    {{ include('ticker/_delete_form.html.twig') }}
{% endblock %}