src/Entity/Description.php
<?php

namespace App\Entity;

use App\Repository\DescriptionRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=DescriptionRepository::class)
 */
class Description
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $logo;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $listdate;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $cik;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $bloomberg;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $figi;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $lei;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $sic;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $country;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $industry;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $sector;

    /**
     * @ORM\Column(type="bigint", nullable=true)
     */
    private $marketcap;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $employees;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $phone;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $ceo;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $url;

    /**
     * @ORM\Column(type="string", length=3000, nullable=true)
     */
    private $description;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $exchange;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $name;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $symbol;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $exchangeSymbol;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $hq_address;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $hq_state;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $hq_country;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $type;

    /**
     * @ORM\Column(type="date", nullable=true)
     */
    private $updated;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $tags;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $similar;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $active;

    /**
     * @ORM\OneToOne(targetEntity=Stock::class, inversedBy="description", cascade={"persist", "remove"})
     * @ORM\JoinColumn(nullable=false, onDelete="CASCADE")
     */
    private $stock;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getLogo(): ?string
    {
        return $this->logo;
    }

    public function setLogo(?string $logo): self
    {
        $this->logo = $logo;

        return $this;
    }

    public function getListdate(): ?string
    {
        return $this->listdate;
    }

    public function setListdate(?string $listdate): self
    {
        $this->listdate = $listdate;

        return $this;
    }

    public function getCik(): ?string
    {
        return $this->cik;
    }

    public function setCik(?string $cik): self
    {
        $this->cik = $cik;

        return $this;
    }

    public function getBloomberg(): ?string
    {
        return $this->bloomberg;
    }

    public function setBloomberg(?string $bloomberg): self
    {
        $this->bloomberg = $bloomberg;

        return $this;
    }

    public function getFigi(): ?string
    {
        return $this->figi;
    }

    public function setFigi(?string $figi): self
    {
        $this->figi = $figi;

        return $this;
    }

    public function getLei(): ?string
    {
        return $this->lei;
    }

    public function setLei(?string $lei): self
    {
        $this->lei = $lei;

        return $this;
    }

    public function getSic(): ?int
    {
        return $this->sic;
    }

    public function setSic(?int $sic): self
    {
        $this->sic = $sic;

        return $this;
    }

    public function getCountry(): ?string
    {
        return $this->country;
    }

    public function setCountry(?string $country): self
    {
        $this->country = $country;

        return $this;
    }

    public function getIndustry(): ?string
    {
        return $this->industry;
    }

    public function setIndustry(?string $industry): self
    {
        $this->industry = $industry;

        return $this;
    }

    public function getSector(): ?string
    {
        return $this->sector;
    }

    public function setSector(?string $sector): self
    {
        $this->sector = $sector;

        return $this;
    }

    public function getMarketcap(): ?string
    {
        return $this->marketcap;
    }

    public function setMarketcap(?string $marketcap): self
    {
        $this->marketcap = $marketcap;

        return $this;
    }

    public function getEmployees(): ?int
    {
        return $this->employees;
    }

    public function setEmployees(?int $employees): self
    {
        $this->employees = $employees;

        return $this;
    }

    public function getPhone(): ?string
    {
        return $this->phone;
    }

    public function setPhone(?string $phone): self
    {
        $this->phone = $phone;

        return $this;
    }

    public function getCeo(): ?string
    {
        return $this->ceo;
    }

    public function setCeo(?string $ceo): self
    {
        $this->ceo = $ceo;

        return $this;
    }

    public function getUrl(): ?string
    {
        return $this->url;
    }

    public function setUrl(?string $url): self
    {
        $this->url = $url;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getExchange(): ?string
    {
        return $this->exchange;
    }

    public function setExchange(?string $exchange): self
    {
        $this->exchange = $exchange;

        return $this;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(?string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getSymbol(): ?string
    {
        return $this->symbol;
    }

    public function setSymbol(?string $symbol): self
    {
        $this->symbol = $symbol;

        return $this;
    }

    public function getExchangeSymbol(): ?string
    {
        return $this->exchangeSymbol;
    }

    public function setExchangeSymbol(?string $exchangeSymbol): self
    {
        $this->exchangeSymbol = $exchangeSymbol;

        return $this;
    }

    public function getHqAddress(): ?string
    {
        return $this->hq_address;
    }

    public function setHqAddress(?string $hq_address): self
    {
        $this->hq_address = $hq_address;

        return $this;
    }

    public function getHqState(): ?string
    {
        return $this->hq_state;
    }

    public function setHqState(?string $hq_state): self
    {
        $this->hq_state = $hq_state;

        return $this;
    }

    public function getHqCountry(): ?string
    {
        return $this->hq_country;
    }

    public function setHqCountry(?string $hq_country): self
    {
        $this->hq_country = $hq_country;

        return $this;
    }

    public function getType(): ?string
    {
        return $this->type;
    }

    public function setType(?string $type): self
    {
        $this->type = $type;

        return $this;
    }

    public function getUpdated(): ?\DateTimeInterface
    {
        return $this->updated;
    }

    public function setUpdated(?\DateTimeInterface $updated): self
    {
        $this->updated = $updated;

        return $this;
    }

    public function getTags(): ?string
    {
        return $this->tags;
    }

    public function setTags(?string $tags): self
    {
        $this->tags = $tags;

        return $this;
    }

    public function getSimilar(): ?string
    {
        return $this->similar;
    }

    public function setSimilar(?string $similar): self
    {
        $this->similar = $similar;

        return $this;
    }

    public function getActive(): ?bool
    {
        return $this->active;
    }

    public function setActive(?bool $active): self
    {
        $this->active = $active;

        return $this;
    }

    public function getStock(): ?Stock
    {
        return $this->stock;
    }

    public function setStock(Stock $stock): self
    {
        $this->stock = $stock;

        return $this;
    }
}

src/Controller/DescriptionController.php
<?php

namespace App\Controller;

use App\Entity\Description;
use App\Form\DescriptionType;
use App\Repository\DescriptionRepository;
use Psr\Log\LoggerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Form\FormError;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("admin/description")
 */
class DescriptionController extends AbstractController
{
    /**
     * @var DescriptionRepository
     */
    private $descriptionRepository;
    /**
     * @var LoggerInterface
     */
    private $logger;

    public function __construct(DescriptionRepository $descriptionRepository, LoggerInterface $logger)
    {
        $this->descriptionRepository=$descriptionRepository;
        $this->logger = $logger;

    }

    /**
     * @Route("/", name="description_index", methods={"GET"})
     * @param Request $request
     * @return Response
     * description admin page
     */
    public function index(Request $request): Response
    {
        $page = $request->query->get('p');
        $pages = null;
        if (!$page || !is_numeric($page)) {
            $page = 0;
        }
        $total = $this->descriptionRepository->count([]);
        $pages = ceil($total / 10);
        return $this->render('description/index.html.twig', [
            'descriptions' =>   $this->descriptionRepository->getPaginated($page),
            'total' => $total,
            'pages' => $pages,
            'page' => $page,
            'symbol' => '',
        ]);
    }
    /**
     * @Route("/search", name="description_search", methods={"POST"})
     * @param Request $request
     * @return Response
     * search descriptions return descriptions with symbol like request[symbol]
     */
    public function search(Request $request): Response
    {
        $symbol = $request->request->get('symbol');
        if(!$symbol || !isset($symbol)){
            $page = 0;
            $total = $this->descriptionRepository->count([]);
            $pages = ceil($total / 10);
            return $this->render('description/index.html.twig', [
                'descriptions' => $this->descriptionRepository->getPaginated($page),
                'total' => $total,
                'pages' => $pages,
                'page' => $page,
                'symbol' => '',
            ]);
        }
        return $this->render('description/index.html.twig', [
            'descriptions' => $this->descriptionRepository->findAllBySymbolLike($symbol),
            'pages' => 0,
            'symbol' => $symbol,
        ]);
    }
    /**
     * @Route("/new", name="description_new", methods={"GET","POST"})
     * create new description
     *
     */
    public function new(Request $request): Response
    {
        $description = new Description();
        $form = $this->createForm(DescriptionType::class, $description);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            if($this->descriptionRepository->findBySymbol($description->getSymbol())){
                $form->addError(new FormError("Entries with the same Date and Stock cannot exist "));
                return $this->render('description/new.html.twig', [
                    'description' => $description,
                    'form' => $form->createView(),
                ]);
            }
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($description);
            $entityManager->flush();

            return $this->redirectToRoute('description_index');
        }

        return $this->render('description/new.html.twig', [
            'description' => $description,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="description_show", methods={"GET"})
     * view description
     */
    public function show(Description $description): Response
    {
        return $this->render('description/show.html.twig', [
            'description' => $description,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="description_edit", methods={"GET","POST"})
     * @param Request $request
     * @param Description $description
     * @return Response
     * update description
     */
    public function edit(Request $request, Description $description): Response
    {
        $form = $this->createForm(DescriptionType::class, $description);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            if($this->descriptionRepository->findOneBySymbolAndNotId($description->getSymbol(),$description->getId())){
                $form->addError(new FormError("Entries with the same Date and Stock cannot exist "));
                return $this->render('description/new.html.twig', [
                    'description' => $description,
                    'form' => $form->createView(),
                ]);
            }
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('description_index');
        }

        return $this->render('description/edit.html.twig', [
            'description' => $description,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="description_delete", methods={"POST"})
     * delete description
     */
    public function delete(Request $request, Description $description): Response
    {
        if ($this->isCsrfTokenValid('', $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($description);
            $entityManager->flush();
        }

        return $this->redirectToRoute('description_index');
    }
}

templates/description/_delete_form.html.twig
<form method="post" action="{{ path('description_delete', {'id': description.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ description.id) }}">
    <button class="btn">Delete</button>
</form>

templates/description/_form.html.twig
{% block javascripts %}
    {{ encore_entry_script_tags('description') }}
{% endblock %}
<div class="text-center container ">
    {{ form_start(form) }}
    {% for error in form.vars.errors %}
        <div class="alert alert-danger">{{ error.message }} </div>
    {% endfor %}
    <div class="form-row">
        <div class="form-group col-6">
            <label for="description_logo">logo</label>
            {{ form_widget(form.logo) }}
            {% for error in form.logo.vars.errors %}
                <div class="alert alert-danger">{{ error.message }} </div>
            {% endfor %}
        </div>
        <div class="form-group col-6">
            <label for="description_listdate">listdate</label>
            {{ form_widget(form.listdate) }}
            {% for error in form.listdate.vars.errors %}
                <div class="alert alert-danger">{{ error.message }} </div>
            {% endfor %}
        </div>
    </div>
    <div class="form-row">
        <div class="form-group col-6">
            <label for="description_cik">cik</label>
            {{ form_widget(form.cik) }}
            {% for error in form.cik.vars.errors %}
                <div class="alert alert-danger">{{ error.message }} </div>
            {% endfor %}
        </div>
        <div class="form-group col-6">
            <label for="description_bloomberg">bloomberg</label>
            {{ form_widget(form.bloomberg) }}
            {% for error in form.bloomberg.vars.errors %}
                <div class="alert alert-danger">{{ error.message }} </div>
            {% endfor %}
        </div>
    </div>
    <div class="form-row">
        <div class="form-group col-6">
            <label for="description_figi">figi</label>
            {{ form_widget(form.figi) }}
            {% for error in form.figi.vars.errors %}
                <div class="alert alert-danger">{{ error.message }} </div>
            {% endfor %}
        </div>
        <div class="form-group col-6">
            <label for="description_lei">lei</label>
            {{ form_widget(form.lei) }}
            {% for error in form.lei.vars.errors %}
                <div class="alert alert-danger">{{ error.message }} </div>
            {% endfor %}
        </div>
    </div>
    <div class="form-row">
        <div class="form-group col-6">
            <label for="description_sic">sic</label>
            {{ form_widget(form.sic) }}
            {% for error in form.sic.vars.errors %}
                <div class="alert alert-danger">{{ error.message }} </div>
            {% endfor %}
        </div>
        <div class="form-group col-6">
            <label for="description_country">country</label>
            {{ form_widget(form.country) }}
            {% for error in form.country.vars.errors %}
                <div class="alert alert-danger">{{ error.message }} </div>
            {% endfor %}
        </div>
    </div>
    <div class="form-row">
        <div class="form-group col-6">
            <label for="description_industry">industry</label>
            {{ form_widget(form.industry) }}
            {% for error in form.industry.vars.errors %}
                <div class="alert alert-danger">{{ error.message }} </div>
            {% endfor %}
        </div>
        <div class="form-group col-6">
            <label for="description_sector">sector</label>
            {{ form_widget(form.sector) }}
            {% for error in form.sector.vars.errors %}
                <div class="alert alert-danger">{{ error.message }} </div>
            {% endfor %}
        </div>
    </div>
    <div class="form-row">
        <div class="form-group col-6">
            <label for="description_marketcap">marketcap</label>
            {{ form_widget(form.marketcap) }}
            {% for error in form.marketcap.vars.errors %}
                <div class="alert alert-danger">{{ error.message }} </div>
            {% endfor %}
        </div>
        <div class="form-group col-6">
            <label for="description_employees">employees</label>
            {{ form_widget(form.employees) }}
            {% for error in form.employees.vars.errors %}
                <div class="alert alert-danger">{{ error.message }} </div>
            {% endfor %}
        </div>
    </div>
    <div class="form-row">
        <div class="form-group col-6">
            <label for="description_phone">phone</label>
            {{ form_widget(form.phone) }}
            {% for error in form.phone.vars.errors %}
                <div class="alert alert-danger">{{ error.message }} </div>
            {% endfor %}
        </div>
        <div class="form-group col-6">
            <label for="description_ceo">ceo</label>
            {{ form_widget(form.ceo) }}
            {% for error in form.ceo.vars.errors %}
                <div class="alert alert-danger">{{ error.message }} </div>
            {% endfor %}
        </div>
    </div>
    <div class="form-row">
        <div class="form-group col-6">
            <label for="description_url">url</label>
            {{ form_widget(form.url) }}
            {% for error in form.url.vars.errors %}
                <div class="alert alert-danger">{{ error.message }} </div>
            {% endfor %}
        </div>
            <div class="form-group col-6">
                <label for="description_exchangeSymbol">exchangeSymbol</label>
                {{ form_widget(form.exchangeSymbol) }}
                {% for error in form.exchangeSymbol.vars.errors %}
                    <div class="alert alert-danger">{{ error.message }} </div>
                {% endfor %}
            </div>
    </div>
    <div class="form-row">
    <div class="form-group col-12">
        <label for="description_description">description</label>
        {{ form_widget(form.description) }}
        {% for error in form.description.vars.errors %}
            <div class="alert alert-danger">{{ error.message }} </div>
        {% endfor %}
    </div>
    </div>
    <div class="form-row">
        <div class="form-group col-6">
            <label for="description_exchange">exchange</label>
            {{ form_widget(form.exchange) }}
            {% for error in form.exchange.vars.errors %}
                <div class="alert alert-danger">{{ error.message }} </div>
            {% endfor %}
        </div>
        <div class="form-group col-6">
            <label for="description_name">name</label>
            {{ form_widget(form.name) }}
            {% for error in form.name.vars.errors %}
                <div class="alert alert-danger">{{ error.message }} </div>
            {% endfor %}
        </div>
    </div>

    <div class="form-group col-6" style="display: none">
        <label for="description_symbol">symbol</label>
        {{ form_widget(form.symbol) }}
        {% for error in form.symbol.vars.errors %}
            <div class="alert alert-danger">{{ error.message }} </div>
        {% endfor %}
    </div>
    <div class="form-row">
        <div class="form-group col-6">
            <label for="description_hq_address">hq_address</label>
            {{ form_widget(form.hq_address) }}
            {% for error in form.hq_address.vars.errors %}
                <div class="alert alert-danger">{{ error.message }} </div>
            {% endfor %}
        </div>
        <div class="form-group col-6">
            <label for="description_hq_state">hq_state</label>
            {{ form_widget(form.hq_state) }}
            {% for error in form.hq_state.vars.errors %}
                <div class="alert alert-danger">{{ error.message }} </div>
            {% endfor %}
        </div>
    </div>
    <div class="form-row">
        <div class="form-group col-6">
            <label for="description_hq_country">hq_country</label>
            {{ form_widget(form.hq_country) }}
            {% for error in form.hq_country.vars.errors %}
                <div class="alert alert-danger">{{ error.message }} </div>
            {% endfor %}
        </div>
        <div class="form-group col-6">
            <label for="description_type">type</label>
            {{ form_widget(form.type) }}
            {% for error in form.type.vars.errors %}
                <div class="alert alert-danger">{{ error.message }} </div>
            {% endfor %}
        </div>
    </div>
    <div class="form-row">
        <div class="form-group col-6">
            <label for="description_updated">updated</label>
            {{ form_widget(form.updated) }}
            {% for error in form.updated.vars.errors %}
                <div class="alert alert-danger">{{ error.message }} </div>
            {% endfor %}
        </div>
        <div class="form-group col-6">
            <label for="description_tags">tags</label>
            {{ form_widget(form.tags) }}
            {% for error in form.tags.vars.errors %}
                <div class="alert alert-danger">{{ error.message }} </div>
            {% endfor %}
        </div>
    </div>
    <div class="form-row">
        <div class="form-group col-6">
            <label for="description_similar">similar</label>
            {{ form_widget(form.similar) }}
            {% for error in form.similar.vars.errors %}
                <div class="alert alert-danger">{{ error.message }} </div>
            {% endfor %}
        </div>
        <div class="custom-control custom-checkbox col-6">
            {{ form_widget(form.active) }}
             <label for="description_active" class="custom-control-label">active</label>

            {% for error in form.active.vars.errors %}
                <div class="alert alert-danger">{{ error.message }} </div>
            {% endfor %}
        </div>
    </div>
    <div class="form-row">
        <div class="form-group col-6">
            <label for="description_stock">stock</label>
            {{ form_widget(form.stock) }}
            {% for error in form.stock.vars.errors %}
                <div class="alert alert-danger">{{ error.message }} </div>
            {% endfor %}
        </div>
    </div>
    <div class="form-row">
        <div class="form-group col-12">
            <button class="btn btn-primary btn-lg">{{ button_label|default('Save') }}</button>
        </div>
    </div>
    {{ form_end(form) }}
</div>

templates/description/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Description{% endblock %}

{% block body %}

    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h1>Edit Description</h1>
        <div class="btn-toolbar mb-2 mb-md-0">
            <div class="btn-group me-2">
                <a href="{{ path('description_index') }}" type="button" class="btn btn-sm btn-outline-info">Back</a>
            </div>
        </div>
    </div>
    {{ include('description/_form.html.twig', {'button_label': 'Update'}) }}

{% endblock %}

templates/description/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Description{% endblock %}

{% block body %}
    <h1>Create new Description</h1>

    {{ include('description/_form.html.twig') }}

    <a href="{{ path('description_index') }}">back to list</a>
{% endblock %}

templates/description/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Description{% endblock %}

{% block body %}
    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h1>Description</h1>
        <div class="btn-toolbar mb-2 mb-md-0">
            <div class="btn-group me-2 btn-group-lg" >
                <a href="{{ path('description_index') }}" type="button" class="btn btn-sm btn-outline-info btn-lg">Back</a>
                <a href="{{ path('description_edit', {'id': description.id}) }}" type="button" class="btn btn-sm btn-outline-secondary btn-lg">Edit</a>
            </div>
        </div>
    </div>
    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ description.id }}</td>
            </tr>
            <tr>
                <th>Logo</th>
                <td>{{ description.logo }}</td>
            </tr>
            <tr>
                <th>Listdate</th>
                <td>{{ description.listdate }}</td>
            </tr>
            <tr>
                <th>Cik</th>
                <td>{{ description.cik }}</td>
            </tr>
            <tr>
                <th>Bloomberg</th>
                <td>{{ description.bloomberg }}</td>
            </tr>
            <tr>
                <th>Figi</th>
                <td>{{ description.figi }}</td>
            </tr>
            <tr>
                <th>Lei</th>
                <td>{{ description.lei }}</td>
            </tr>
            <tr>
                <th>Sic</th>
                <td>{{ description.sic }}</td>
            </tr>
            <tr>
                <th>Country</th>
                <td>{{ description.country }}</td>
            </tr>
            <tr>
                <th>Industry</th>
                <td>{{ description.industry }}</td>
            </tr>
            <tr>
                <th>Sector</th>
                <td>{{ description.sector }}</td>
            </tr>
            <tr>
                <th>Marketcap</th>
                <td>{{ description.marketcap }}</td>
            </tr>
            <tr>
                <th>Employees</th>
                <td>{{ description.employees }}</td>
            </tr>
            <tr>
                <th>Phone</th>
                <td>{{ description.phone }}</td>
            </tr>
            <tr>
                <th>Ceo</th>
                <td>{{ description.ceo }}</td>
            </tr>
            <tr>
                <th>Url</th>
                <td>{{ description.url }}</td>
            </tr>
            <tr>
                <th>Description</th>
                <td>{{ description.description }}</td>
            </tr>
            <tr>
                <th>Exchange</th>
                <td>{{ description.exchange }}</td>
            </tr>
            <tr>
                <th>Name</th>
                <td>{{ description.name }}</td>
            </tr>
            <tr>
                <th>Symbol</th>
                <td>{{ description.symbol }}</td>
            </tr>
            <tr>
                <th>ExchangeSymbol</th>
                <td>{{ description.exchangeSymbol }}</td>
            </tr>
            <tr>
                <th>Hq_address</th>
                <td>{{ description.hqAddress }}</td>
            </tr>
            <tr>
                <th>Hq_state</th>
                <td>{{ description.hqState }}</td>
            </tr>
            <tr>
                <th>Hq_country</th>
                <td>{{ description.hqCountry }}</td>
            </tr>
            <tr>
                <th>Type</th>
                <td>{{ description.type }}</td>
            </tr>
            <tr>
                <th>Updated</th>
                <td>{{ description.updated ? description.updated|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Tags</th>
                <td>{{ description.tags }}</td>
            </tr>
            <tr>
                <th>Similar</th>
                <td>{{ description.similar }}</td>
            </tr>
            <tr>
                <th>Active</th>
                <td>{{ description.active ? 'Yes' : 'No' }}</td>
            </tr>
        </tbody>
    </table>
{% endblock %}